'use strict';

module.exports = [
  'SELECT',
  'tags.id AS tid,',
  'tags.name AS tags_name,',
  'challenges.id AS chal_id,',
  'challenges.date AS chal_date,',
  'challenges.title AS chal_title,',
  'challenges.description AS chal_description,',
  'organisations.name AS org_name,',
  'organisations.id AS org_id',
  'from',
  'challenges',
  'JOIN',
  'tags_challenges',
  'ON',
  'tags_challenges.challenges_id = challenges.id',
  'JOIN',
  'tags',
  'ON',
  'tags_challenges.tags_id = tags.id',
  'JOIN',
  'organisations',
  'ON',
  'challenges.org_id = organisations.id',
  'WHERE',
  'challenges.active = TRUE',
  'AND',
  'tags.active = TRUE;'
].join(' ');
